//  CHOUREY ONE CONSTANTS

export const GET_CHOUREY_ONE_LIST_REQUEST = "GET_CHOUREY_ONE_LIST_REQUEST"
export const GET_CHOUREY_ONE_LIST_SUCCESS = "GET_CHOUREY_ONE_LIST_SUCCESS"
export const GET_CHOUREY_ONE_LIST_FAIL = "GET_CHOUREY_ONE_LIST_FAIL"
export const GET_CHOUREY_ONE_LIST_RESET = "GET_CHOUREY_ONE_LIST_RESET"

export const CREATE_CHOUREY_ONE_REQUEST = "CREATE_CHOUREY_ONE_REQUEST"
export const CREATE_CHOUREY_ONE_SUCCESS = "CREATE_CHOUREY_ONE_SUCCESS"
export const CREATE_CHOUREY_ONE_FAIL = "CREATE_CHOUREY_ONE_FAIL"
export const CREATE_CHOUREY_ONE_RESET = "CREATE_CHOUREY_ONE_RESET"

export const CHOUREY_ONE_DETAIL_REQUEST = "CHOUREY_ONE_DETAIL_REQUEST"
export const CHOUREY_ONE_DETAIL_SUCCESS = "CHOUREY_ONE_DETAIL_SUCCESS"
export const CHOUREY_ONE_DETAIL_FAIL = "CHOUREY_ONE_DETAIL_FAIL"
export const CHOUREY_ONE_DETAIL_RESET = "CHOUREY_ONE_DETAIL_RESET"

export const CHOUREY_ONE_DELETE_REQUEST = "CHOUREY_ONE_DELETE_REQUEST"
export const CHOUREY_ONE_DELETE_SUCCESS = "CHOUREY_ONE_DELETE_SUCCESS"
export const CHOUREY_ONE_DELETE_FAIL = "CHOUREY_ONE_DELETE_FAIL"
export const CHOUREY_ONE_DELETE_RESET = "CHOUREY_ONE_DELETE_RESET"

export const MULTIPLE_CHOUREY_ONE_DELETE_REQUEST = "MULTIPLE_CHOUREY_ONE_DELETE_REQUEST"
export const MULTIPLE_CHOUREY_ONE_DELETE_SUCCESS = "MULTIPLE_CHOUREY_ONE_DELETE_SUCCESS"
export const MULTIPLE_CHOUREY_ONE_DELETE_FAIL = "MULTIPLE_CHOUREY_ONE_DELETE_FAIL"
export const MULTIPLE_CHOUREY_ONE_DELETE_RESET = "MULTIPLE_CHOUREY_ONE_DELETE_RESET"

export const UPDATE_CHOUREY_ONE_REQUEST = "UPDATE_CHOUREY_ONE_REQUEST"
export const UPDATE_CHOUREY_ONE_SUCCESS = "UPDATE_CHOUREY_ONE_SUCCESS"
export const UPDATE_CHOUREY_ONE_FAIL = "UPDATE_CHOUREY_ONE_FAIL"
export const UPDATE_CHOUREY_ONE_RESET = "UPDATE_CHOUREY_ONE_RESET"

//  CHOUREY TWO CONSTANTS

export const GET_CHOUREY_TWO_LIST_REQUEST = "GET_CHOUREY_TWO_LIST_REQUEST"
export const GET_CHOUREY_TWO_LIST_SUCCESS = "GET_CHOUREY_TWO_LIST_SUCCESS"
export const GET_CHOUREY_TWO_LIST_FAIL = "GET_CHOUREY_TWO_LIST_FAIL"
export const GET_CHOUREY_TWO_LIST_RESET = "GET_CHOUREY_TWO_LIST_RESET"

export const CREATE_CHOUREY_TWO_REQUEST = "CREATE_CHOUREY_TWO_REQUEST"
export const CREATE_CHOUREY_TWO_SUCCESS = "CREATE_CHOUREY_TWO_SUCCESS"
export const CREATE_CHOUREY_TWO_FAIL = "CREATE_CHOUREY_TWO_FAIL"
export const CREATE_CHOUREY_TWO_RESET = "CREATE_CHOUREY_TWO_RESET"

export const CHOUREY_TWO_DETAIL_REQUEST = "CHOUREY_TWO_DETAIL_REQUEST"
export const CHOUREY_TWO_DETAIL_SUCCESS = "CHOUREY_TWO_DETAIL_SUCCESS"
export const CHOUREY_TWO_DETAIL_FAIL = "CHOUREY_TWO_DETAIL_FAIL"
export const CHOUREY_TWO_DETAIL_RESET = "CHOUREY_TWO_DETAIL_RESET"

export const CHOUREY_TWO_DELETE_REQUEST = "CHOUREY_TWO_DELETE_REQUEST"
export const CHOUREY_TWO_DELETE_SUCCESS = "CHOUREY_TWO_DELETE_SUCCESS"
export const CHOUREY_TWO_DELETE_FAIL = "CHOUREY_TWO_DELETE_FAIL"
export const CHOUREY_TWO_DELETE_RESET = "CHOUREY_TWO_DELETE_RESET"

export const MULTIPLE_CHOUREY_TWO_DELETE_REQUEST = "MULTIPLE_CHOUREY_TWO_DELETE_REQUEST"
export const MULTIPLE_CHOUREY_TWO_DELETE_SUCCESS = "MULTIPLE_CHOUREY_TWO_DELETE_SUCCESS"
export const MULTIPLE_CHOUREY_TWO_DELETE_FAIL = "MULTIPLE_CHOUREY_TWO_DELETE_FAIL"
export const MULTIPLE_CHOUREY_TWO_DELETE_RESET = "MULTIPLE_CHOUREY_TWO_DELETE_RESET"

export const UPDATE_CHOUREY_TWO_REQUEST = "UPDATE_CHOUREY_TWO_REQUEST"
export const UPDATE_CHOUREY_TWO_SUCCESS = "UPDATE_CHOUREY_TWO_SUCCESS"
export const UPDATE_CHOUREY_TWO_FAIL = "UPDATE_CHOUREY_TWO_FAIL"
export const UPDATE_CHOUREY_TWO_RESET = "UPDATE_CHOUREY_TWO_RESET"