//  COMMENT CONSTANTS

export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST"
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL"
export const GET_COMMENT_RESET = "GET_COMMENT_RESET"

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL"
export const ADD_COMMENT_RESET = "ADD_COMMENT_RESET"

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL"
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET"

export const GET_COMMENT_BY_MEDIA_REQUEST = "GET_COMMENT_BY_MEDIA_REQUEST"
export const GET_COMMENT_BY_MEDIA_SUCCESS = "GET_COMMENT_BY_MEDIA_SUCCESS"
export const GET_COMMENT_BY_MEDIA_FAIL = "GET_COMMENT_BY_MEDIA_FAIL"
export const GET_COMMENT_BY_MEDIA_RESET = "GET_COMMENT_BY_MEDIA_RESET"