//  COMMON CONTENTS CONSTANTS

export const GET_COMMON_CONTENTS_LIST_REQUEST = "GET_COMMON_CONTENTS_LIST_REQUEST"
export const GET_COMMON_CONTENTS_LIST_SUCCESS = "GET_COMMON_CONTENTS_LIST_SUCCESS"
export const GET_COMMON_CONTENTS_LIST_FAIL = "GET_COMMON_CONTENTS_LIST_FAIL"
export const GET_COMMON_CONTENTS_LIST_RESET = "GET_COMMON_CONTENTS_LIST_RESET"

export const CREATE_COMMON_CONTENTS_REQUEST = "CREATE_COMMON_CONTENTS_REQUEST"
export const CREATE_COMMON_CONTENTS_SUCCESS = "CREATE_COMMON_CONTENTS_SUCCESS"
export const CREATE_COMMON_CONTENTS_FAIL = "CREATE_COMMON_CONTENTS_FAIL"
export const CREATE_COMMON_CONTENTS_RESET = "CREATE_COMMON_CONTENTS_RESET"

export const UPDATE_COMMON_CONTENTS_REQUEST = "UPDATE_COMMON_CONTENTS_REQUEST"
export const UPDATE_COMMON_CONTENTS_SUCCESS = "UPDATE_COMMON_CONTENTS_SUCCESS"
export const UPDATE_COMMON_CONTENTS_FAIL = "UPDATE_COMMON_CONTENTS_FAIL"
export const UPDATE_COMMON_CONTENTS_RESET = "UPDATE_COMMON_CONTENTS_RESET"

export const GET_COMMON_CONTENTS_DETAIL_REQUEST = "GET_COMMON_CONTENTS_DETAIL_REQUEST"
export const GET_COMMON_CONTENTS_DETAIL_SUCCESS = "GET_COMMON_CONTENTS_DETAIL_SUCCESS"
export const GET_COMMON_CONTENTS_DETAIL_FAIL = "GET_COMMON_CONTENTS_DETAIL_FAIL"
export const GET_COMMON_CONTENTS_DETAIL_RESET = "GET_COMMON_CONTENTS_DETAIL_RESET"

export const DELETE_COMMON_CONTENTS_REQUEST = "DELETE_COMMON_CONTENTS_REQUEST"
export const DELETE_COMMON_CONTENTS_SUCCESS = "DELETE_COMMON_CONTENTS_SUCCESS"
export const DELETE_COMMON_CONTENTS_FAIL = "DELETE_COMMON_CONTENTS_FAIL"
export const DELETE_COMMON_CONTENTS_RESET = "DELETE_COMMON_CONTENTS_RESET"