//  DEVICE MAPPING CONSTANTS

export const GET_DEVICE_MAPPING_LIST_REQUEST = "GET_DEVICE_MAPPING_LIST_REQUEST"
export const GET_DEVICE_MAPPING_LIST_SUCCESS = "GET_DEVICE_MAPPING_LIST_SUCCESS"
export const GET_DEVICE_MAPPING_LIST_FAIL = "GET_DEVICE_MAPPING_LIST_FAIL"
export const GET_DEVICE_MAPPING_LIST_RESET = "GET_DEVICE_MAPPING_LIST_RESET"

export const ASSIGN_DEVICE_MAPPING_LIST_REQUEST = "ASSIGN_DEVICE_MAPPING_LIST_REQUEST"
export const ASSIGN_DEVICE_MAPPING_LIST_SUCCESS = "ASSIGN_DEVICE_MAPPING_LIST_SUCCESS"
export const ASSIGN_DEVICE_MAPPING_LIST_FAIL = "ASSIGN_DEVICE_MAPPING_LIST_FAIL"
export const ASSIGN_DEVICE_MAPPING_LIST_RESET = "ASSIGN_DEVICE_MAPPING_LIST_RESET"

export const UPDATE_DEVICE_MAPPING_LIST_REQUEST = "UPDATE_DEVICE_MAPPING_LIST_REQUEST"
export const UPDATE_DEVICE_MAPPING_LIST_SUCCESS = "UPDATE_DEVICE_MAPPING_LIST_SUCCESS"
export const UPDATE_DEVICE_MAPPING_LIST_FAIL = "UPDATE_DEVICE_MAPPING_LIST_FAIL"
export const UPDATE_DEVICE_MAPPING_LIST_RESET = "UPDATE_DEVICE_MAPPING_LIST_RESET"

export const DELETE_DEVICE_MAPPING_LIST_REQUEST = "DELETE_DEVICE_MAPPING_LIST_REQUEST"
export const DELETE_DEVICE_MAPPING_LIST_SUCCESS = "DELETE_DEVICE_MAPPING_LIST_SUCCESS"
export const DELETE_DEVICE_MAPPING_LIST_FAIL = "DELETE_DEVICE_MAPPING_LIST_FAIL"
export const DELETE_DEVICE_MAPPING_LIST_RESET = "DELETE_DEVICE_MAPPING_LIST_RESET"