//  DISASTER CONSTANTS

export const GET_DISASTER_LIST_REQUEST = "GET_DISASTER_LIST_REQUEST"
export const GET_DISASTER_LIST_SUCCESS = "GET_DISASTER_LIST_SUCCESS"
export const GET_DISASTER_LIST_FAIL = "GET_DISASTER_LIST_FAIL"
export const GET_DISASTER_LIST_RESET = "GET_DISASTER_LIST_RESET"

export const CREATE_DISASTER_REQUEST = "CREATE_DISASTER_REQUEST"
export const CREATE_DISASTER_SUCCESS = "CREATE_DISASTER_SUCCESS"
export const CREATE_DISASTER_FAIL = "CREATE_DISASTER_FAIL"
export const CREATE_DISASTER_RESET = "CREATE_DISASTER_RESET"

export const DISASTER_DETAIL_REQUEST = "DISASTER_DETAIL_REQUEST"
export const DISASTER_DETAIL_SUCCESS = "DISASTER_DETAIL_SUCCESS"
export const DISASTER_DETAIL_FAIL = "DISASTER_DETAIL_FAIL"
export const DISASTER_DETAIL_RESET = "DISASTER_DETAIL_RESET"

export const DISASTER_DELETE_REQUEST = "DISASTER_DELETE_REQUEST"
export const DISASTER_DELETE_SUCCESS = "DISASTER_DELETE_SUCCESS"
export const DISASTER_DELETE_FAIL = "DISASTER_DELETE_FAIL"
export const DISASTER_DELETE_RESET = "DISASTER_DELETE_RESET"

export const MULTIPLE_DISASTER_DELETE_REQUEST = "MULTIPLE_DISASTER_DELETE_REQUEST"
export const MULTIPLE_DISASTER_DELETE_SUCCESS = "MULTIPLE_DISASTER_DELETE_SUCCESS"
export const MULTIPLE_DISASTER_DELETE_FAIL = "MULTIPLE_DISASTER_DELETE_FAIL"
export const MULTIPLE_DISASTER_DELETE_RESET = "MULTIPLE_DISASTER_DELETE_RESET"

export const UPDATE_DISASTER_REQUEST = "DISASTER_DELETE_REQUEST"
export const UPDATE_DISASTER_SUCCESS = "UPDATE_DISASTER_SUCCESS"
export const UPDATE_DISASTER_FAIL = "UPDATE_DISASTER_FAIL"
export const UPDATE_DISASTER_RESET = "UPDATE_DISASTER_RESET"