//  FILE CONSTANTS

export const DELETE_MEDIA_FILE_REQUEST = "DELETE_MEDIA_FILE_REQUEST"
export const DELETE_MEDIA_FILE_SUCCESS = "DELETE_MEDIA_FILE_SUCCESS"
export const DELETE_MEDIA_FILE_FAIL = "DELETE_MEDIA_FILE_FAIL"
export const DELETE_MEDIA_FILE_RESET = "DELETE_MEDIA_FILE_RESET"
