// Menu Constants

export const MENU_LIST_REQUEST = "MENU_LIST_REQUEST"
export const MENU_LIST_SUCCESS = "MENU_LIST_SUCCESS"
export const MENU_LIST_FAIL = "MENU_LIST_FAIL"
export const MENU_LIST_RESET = "MENU_LIST_RESET"

export const UPDATE_MENU_LIST_REQUEST = "UPDATE_MENU_LIST_REQUEST"
export const UPDATE_MENU_LIST_SUCCESS = "UPDATE_MENU_LIST_SUCCESS"
export const UPDATE_MENU_LIST_FAIL = "UPDATE_MENU_LIST_FAIL"
export const UPDATE_MENU_LIST_RESET = "UPDATE_MENU_LIST_RESET"