// SAFETY DECLARATION CONSTANTS

export const SAFETY_DECLARATION_LIST_REQUEST = "SAFETY_DECLARATION_LIST_REQUEST"
export const SAFETY_DECLARATION_LIST_SUCCESS = "SAFETY_DECLARATION_LIST_SUCCESS"
export const SAFETY_DECLARATION_LIST_FAIL = "SAFETY_DECLARATION_LIST_FAIL"
export const SAFETY_DECLARATION_LIST_RESET = "MENU_SAFETY_DECLARATION_LIST_RESET"

export const CREATE_SAFETY_DECLARATION_REQUEST = "CREATE_SAFETY_DECLARATION_REQUEST"
export const CREATE_SAFETY_DECLARATION_SUCCESS = "CREATE_SAFETY_DECLARATION_SUCCESS"
export const CREATE_SAFETY_DECLARATION_FAIL = "CREATE_SAFETY_DECLARATION_FAIL"
export const CREATE_SAFETY_DECLARATION_RESET = "CREATE_SAFETY_DECLARATION_RESET"

export const UPDATE_SAFETY_DECLARATION_REQUEST = "UPDATE_SAFETY_DECLARATION_REQUEST"
export const UPDATE_SAFETY_DECLARATION_SUCCESS = "UPDATE_SAFETY_DECLARATION_SUCCESS"
export const UPDATE_SAFETY_DECLARATION_FAIL = "UPDATE_SAFETY_DECLARATION_FAIL"
export const UPDATE_SAFETY_DECLARATION_RESET = "UPDATE_SAFETY_DECLARATION_RESET"

export const SAFETY_DECLARATION_DETAIL_REQUEST = "SAFETY_DECLARATION_DETAIL_REQUEST"
export const SAFETY_DECLARATION_DETAIL_SUCCESS = "SAFETY_DECLARATION_DETAIL_SUCCESS"
export const SAFETY_DECLARATION_DETAIL_FAIL = "SAFETY_DECLARATION_DETAIL_FAIL"
export const SAFETY_DECLARATION_DETAIL_RESET = "SAFETY_DECLARATION_DETAIL_RESET"

export const SAFETY_DECLARATION_DELETE_REQUEST = "SAFETY_DECLARATION_DELETE_REQUEST"
export const SAFETY_DECLARATION_DELETE_SUCCESS = "SAFETY_DECLARATION_DELETE_SUCCESS"
export const SAFETY_DECLARATION_DELETE_FAIL = "SAFETY_DECLARATION_DELETE_FAIL"
export const SAFETY_DECLARATION_DELETE_RESET = "SAFETY_DECLARATION_DELETE_RESET"
