// SITE CONSTANTS

// -- SUPER ADMIN --

export const SITE_CODE_CREATE_REQUEST = "SITE_CODE_CREATE_REQUEST"
export const SITE_CODE_CREATE_SUCCESS = "SITE_CODE_CREATE_SUCCESS"
export const SITE_CODE_CREATE_FAIL = "SITE_CODE_CREATE_FAIL"
export const SITE_CODE_CREATE_RESET = "SITE_CODE_CREATE_RESET"

export const SITE_ALL_LIST_REQUEST = "SITE_ALL_LIST_REQUEST";
export const SITE_ALL_LIST_SUCCESS = "SITE_ALL_LIST_SUCCESS";
export const SITE_ALL_LIST_FAIL = "SITE_ALL_LIST_FAIL"

export const SITE_UNASSIGNED_LIST_REQUEST = "SITE_UNASSIGNED_LIST_REQUEST";
export const SITE_UNASSIGNED_LIST_SUCCESS = "SITE_UNASSIGNED_LIST_SUCCESS";
export const SITE_UNASSIGNED_LIST_FAIL = "SITE_UNASSIGNED_LIST_FAIL";

export const SITE_CODE_DELETE_REQUEST = "SITE_CODE_DELETE_REQUEST"
export const SITE_CODE_DELETE_SUCCESS = "SITE_CODE_DELETE_SUCCESS"
export const SITE_CODE_DELETE_FAIL = "SITE_CODE_DELETE_FAIL"
export const SITE_CODE_DELETE_RESET = "SITE_CODE_DELETE_RESET"

export const ALL_SITES_SPACE_LIST_REQUEST = "ALL_SITES_SPACE_LIST_REQUEST"
export const ALL_SITES_SPACE_LIST_SUCCESS = "ALL_SITES_SPACE_LIST_SUCCESS"
export const ALL_SITES_SPACE_LIST_FAIL = "ALL_SITES_SPACE_LIST_FAIL"
export const ALL_SITES_SPACE_LIST_RESET = "ALL_SITES_SPACE_LIST_RESET"

export const SITE_SPACE_DETAIL_REQUEST = "SITE_SPACE_DETAIL_REQUEST"
export const SITE_SPACE_DETAIL_SUCCESS = "SITE_SPACE_DETAIL_SUCCESS"
export const SITE_SPACE_DETAIL_FAIL = "SITE_SPACE_DETAIL_FAIL"
export const SITE_SPACE_DETAIL_RESET = "SITE_SPACE_DETAIL_RESET"

export const ASSIGN_SITE_SPACE_REQUEST = "ASSIGN_SITE_SPACE_REQUEST"
export const ASSIGN_SITE_SPACE_SUCCESS = "ASSIGN_SITE_SPACE_SUCCESS"
export const ASSIGN_SITE_SPACE_FAIL = "ASSIGN_SITE_SPACE_FAIL"
export const ASSIGN_SITE_SPACE_RESET = "ASSIGN_SITE_SPACE_RESET"

// -- ADMIN & SUBADMIN --

export const SITE_LIST_REQUEST = "SITE_LIST_REQUEST"
export const SITE_LIST_SUCCESS = "SITE_LIST_SUCCESS"
export const SITE_LIST_FAIL = "SITE_LIST_FAIL"

export const SITE_CODE_VALIDATION_REQUEST = "SITE_CODE_VALIDATION_REQUEST"
export const SITE_CODE_VALIDATION_SUCCESS = "SITE_CODE_VALIDATION_SUCCESS"
export const SITE_CODE_VALIDATION_FAIL = "SITE_CODE_VALIDATION_FAIL"
export const SITE_CODE_VALIDATION_RESET = "SITE_CODE_VALIDATION_RESET"

export const SITE_INFORMATION_CREATE_REQUEST = "SITE_INFORMATION_CREATE_REQUEST"
export const SITE_INFORMATION_CREATE_SUCCESS = "SITE_INFORMATION_CREATE_SUCCESS"
export const SITE_INFORMATION_CREATE_FAIL = "SITE_INFORMATION_CREATE_FAIL"
export const SITE_INFORMATION_CREATE_RESET = "SITE_INFORMATION_CREATE_RESET"

export const SITE_INFORMATION_UPDATE_REQUEST = "SITE_INFORMATION_UPDATE_REQUEST"
export const SITE_INFORMATION_UPDATE_SUCCESS = "SITE_INFORMATION_UPDATE_SUCCESS"
export const SITE_INFORMATION_UPDATE_FAIL = "SITE_INFORMATION_UPDATE_FAIL"
export const SITE_INFORMATION_UPDATE_RESET = "SITE_INFORMATION_UPDATE_RESET"

export const SITE_INFORMATION_DETAIL_REQUEST = "SITE_INFORMATION_DETAIL_REQUEST"
export const SITE_INFORMATION_DETAIL_SUCCESS = "SITE_INFORMATION_DETAIL_SUCCESS"
export const SITE_INFORMATION_DETAIL_FAIL = "SITE_INFORMATION_DETAIL_FAIL"

export const SITE_DETAIL_BY_QR_REQUEST = "SITE_DETAIL_BY_QR_REQUEST"
export const SITE_DETAIL_BY_QR_SUCCESS = "SITE_DETAIL_BY_QR_SUCCESS"
export const SITE_DETAIL_BY_QR_FAIL = "SITE_DETAIL_BY_QR_FAIL"
export const SITE_DETAIL_BY_QR_RESET = "SITE_DETAIL_BY_QR_RESET"