//  SUB ADMIN CONSTANTS
export const SUB_ADMIN_LIST_REQUEST = "SUB_ADMIN_LIST_REQUEST";
export const SUB_ADMIN_LIST_SUCCESS = "SUB_ADMIN_LIST_SUCCESS";
export const SUB_ADMIN_LIST_FAIL = "SUB_ADMIN_LIST_FAIL";
export const SUB_ADMIN_LIST_RESET = "SUB_ADMIN_LIST_RESET";

export const SUB_ADMIN_ASSIGN_REQUEST = "SUB_ADMIN_ASSIGN_REQUEST"
export const SUB_ADMIN_ASSIGN_SUCCESS = "SUB_ADMIN_ASSIGN_SUCCESS"
export const SUB_ADMIN_ASSIGN_FAIL = "SUB_ADMIN_ASSIGN_FAIL"
export const SUB_ADMIN_ASSIGN_RESET = "SUB_ADMIN_ASSIGN_RESET"

export const SUB_ADMIN_DELETE_REQUEST = "SUB_ADMIN_DELETE_REQUEST"
export const SUB_ADMIN_DELETE_SUCCESS = "SUB_ADMIN_DELETE_SUCCESS"
export const SUB_ADMIN_DELETE_FAIL = "SUB_ADMIN_DELETE_FAIL"
export const SUB_ADMIN_DELETE_RESET = "SUB_ADMIN_DELETE_RESET"