//  USER BOARD CONSTANTS
export const GET_USERBOARD_REQUEST = "GET_USERBOARD_REQUEST";
export const GET_USERBOARD_SUCCESS = "GET_USERBOARD_SUCCESS";
export const GET_USERBOARD_FAIL = "GET_USERBOARD_FAIL";
export const GET_USERBOARD_RESET = "GET_USERBOARD_RESET";
